package yasearcher;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.net.URL;
import java.net.URLEncoder;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

public class YaSearcher {

    private static final String YA_URL = "https://xmlsearch.yandex.com/xmlsearch?l10n=en&";
    private static final String ENC = "UTF-8";
    private static final String AND = "&";
    private static final int pages = 5; // 0 - booking, 1 - turpravda, 2 - tripadvisor, 3 - tophotels, 4- tury
    private String user;
    private String key;

    /**
     * Constructor
     * @param user your Yandex username
     * @param key key generated by Yandex.XML
     */
    private YaSearcher(final String user, final String key) {
        this.user = user;
        this.key = key;
    }

    /**
     * Retrieve Yandex.XML response stream via GET request
     * @param query search query
     * @param pageNumber number of search page
     * @return Yandex.XML response stream
     * @throws IOException input/output exception
     */
    public InputStream retrieveResponseViaGetRequest(
        final String query,
        final int pageNumber
    ) throws IOException {

        final StringBuilder address = new StringBuilder(YA_URL);
        address.append("user=").append(user).append(AND)
            .append("key=").append(key).append(AND)
            .append("query=").append(URLEncoder.encode(query, ENC)).append(AND)
            .append("page=").append(pageNumber);final URL url = new URL(address.toString());
        return url.openStream();
    }
    
    public YaPage loadYaPage(final String query, final int pageNumber)
    throws IOException, SAXException {

        final YaPage result = new YaPage(query, pageNumber);
        final XMLReader xmlReader = XMLReaderFactory.createXMLReader();
        xmlReader.setContentHandler(new YaHandler(result));
        xmlReader.parse(
            new InputSource(
                this.retrieveResponseViaGetRequest(query, pageNumber)
            )
        );
        return result;
    }

    public static String[] search(String user, String key, String query) throws IOException, SAXException {

        String[] res = new String[pages];
        final YaSearcher searcher = new YaSearcher(user, key);
        
        for (int i = 0; i < 5; ++i) {
        
            final YaPage result = searcher.loadYaPage(query, i);
            
            for (YaItem item : result.getYaItems()) {
                String url = item.getUrl();

                if (url.contains("booking") && res[0] == null) {
                    res[0] = url;
                    continue;
                }
            
                if (url.contains("turpravda") && res[1] == null) {
                    res[1] = url;
                    continue;
                }
            
                if (url.contains("tripadvisor") && res[2] == null) {
                    res[2] = url;
                    continue;
                }
            
                if (url.contains("tophotels") && res[3] == null) {
                    res[3] = url;
                    continue;
                }
                
                if (url.contains("tury") && url.contains("hotel") && res[4] == null) {
                    res[4] = url;
                    continue;
                }

            }
        }
        
        return res;
    }
 
}